import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthTokenProvider from "./context";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthTokenProvider>
          {children}
        </AuthTokenProvider>
      </body>
    </html>
  );
}
